import { existsSync, readFileSync, writeFileSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { CliError } from "../errors.js";
import { zshCompletionScript } from "./completion.js";

const completionBlockStart = "# >>> livetree completions >>>";
const completionBlockEnd = "# <<< livetree completions <<<";

type InstallToolsOptions = {
  homeDir?: string;
};

export function installTools(target: string, options: InstallToolsOptions = {}): void {
  if (target !== "tools") {
    throw new CliError("Usage: lt install tools");
  }

  const homeDir = options.homeDir ?? os.homedir();
  const zshrcPath = path.join(homeDir, ".zshrc");
  const block = `${completionBlockStart}
# Generated by lt install tools. Re-run that command to refresh this block.
${zshCompletionScript()}
${completionBlockEnd}`;
  const existing = existsSync(zshrcPath) ? readFileSync(zshrcPath, "utf8") : "";
  const next = upsertManagedBlock(existing, block);

  writeFileSync(zshrcPath, next, "utf8");
  console.log(`Installed livetree zsh completion in ${zshrcPath}`);
}

export function upsertManagedBlock(source: string, block: string): string {
  const pattern = new RegExp(`${escapeRegExp(completionBlockStart)}[\\s\\S]*?${escapeRegExp(completionBlockEnd)}`);
  const trimmedBlock = block.trim();

  if (pattern.test(source)) {
    return source.replace(pattern, trimmedBlock);
  }

  const separator = source.length > 0 && !source.endsWith("\n") ? "\n\n" : source.length > 0 ? "\n" : "";
  return `${source}${separator}${trimmedBlock}\n`;
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
